apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:master
      rolearn: arn:aws:iam::578327884334:role/UdacityFlaskDeployCBKubectlRoles
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::578327884334:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-OR919755296P
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-15T20:03:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "185061"
  uid: b40d2dc8-1b5c-47dc-850f-6b805ca3fd52
